<?php

namespace Enfi\CienciasDoAmbiente\CommonEntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PontoDeColetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PontoDeColetaRepository extends EntityRepository
{
    public function getMaxIdFixo() {
        $result =  $this->getEntityManager()
                    ->createQuery("SELECT MAX(p.idFixo) FROM EnfiCienciasDoAmbienteCommonEntitiesBundle:PontoDeColeta p")->getSingleResult();
        return (int) $result[1];
    }

    public function getMaxRevision($idFixo) {
        $result =  $this->getEntityManager()
                    ->createQuery("SELECT MAX(p.revision) FROM EnfiCienciasDoAmbienteCommonEntitiesBundle:PontoDeColeta p WHERE p.idFixo = '$idFixo'")->getSingleResult();
        return (int) $result[1];
    }
}
