# HWIOAuthBundle
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
facebook_login:
    pattern: /login/check-facebook

# Custom
enfi_ciencias_do_ambiente_site:
    resource: "@EnfiCienciasDoAmbienteSiteBundle/Controller/"
    type:     annotation
    prefix:   /

enfi_ciencias_do_ambiente_api:
    resource: "@EnfiCienciasDoAmbienteApiBundle/Controller/"
    type:     annotation
    prefix:   /api/

enfi_ciencias_do_ambiente_commonentities:
    resource: "@EnfiCienciasDoAmbienteCommonEntitiesBundle/Controller/"
    type:     annotation
    prefix:   /


# Security
_logout:
    path: /logout
